version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: currency_db
    ports:
      - "3306:3306"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
